TARGET = "base_none"

PLATFORM_BUILD_PATH = ${PLATFORM_PATH}/out
PLATFORM_TARGET_PLAT_DIR = ${PLATFORM_PATH}/makerules
PLATFORM_TARGET_RELEASE  = ${PLATFORM_PATH}/release

export PLATFORM_BUILD_PATH PLATFORM_TARGET_PLAT_DIR PLATFORM_TARGET_RELEASE
export TARGET

