PLATFORM_UBOOT_TARGET_DIRECTORY = ${PLATFORM_RELEASE_DIRECTORY}/u-boot
PLATFORM_KERNEL_TARGET_DIRECTORY = ${PLATFORM_RELEASE_DIRECTORY}/kernel
UBOOT_PATH = u-boot/u-boot-2015-07-rc2
KERNEL_PATH = kernel/linux-3.10.96

PLATFORM_RELEASE_VERSION ?= 2.0.${PLATFORM_RELEASE_SVN_VERSION}
UBOOT_RELEASE_VERSION=${PLATFORM_RELEASE_VERSION}
KERNEL_RELEASE_VERSION=${PLATFORM_RELEASE_VERSION}
UBOOT_BUILD_OBJ_PATH=${ITARGE_BUILD_OBJS_PATH}/uboot
KERNEL_BUILD_OBJ_PATH=${ITARGE_BUILD_OBJS_PATH}/kernel
PACKAGE_BUILE_OBJ_PATH=${ITARGE_BUILD_OBJS_PATH}/package

export KERNEL_PATH UBOOT_PATH UBOOT_BUILD_OBJ_PATH KERNEL_BUILD_OBJ_PATH PACKAGE_BUILE_OBJ_PATH
export UBOOT_RELEASE_VERSION KERNEL_RELEASE_VERSION PLATFORM_UBOOT_TARGET_DIRECTORY PLATFORM_KERNEL_TARGET_DIRECTORY
export PLATFORM_RELEASE_VERSION

unexport ROOT_DIR
unexport TARGET
